name: "Practice 1: ðŸ”” Issues Notification"

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  notigication:
    name: ðŸ”” Notify
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš¨ Alert
        run: echo "An issue has been ${{ github.event_name }}"
