name: ğŸ”” Issues Notification

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  notigication:
    name: ğŸ”” Notify
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš¨ Alert
        run: echo "An issue has been ${{ github.event_name }}"
